const express = require('express');
const router = express.Router();

/**
 * File generated by the Express app template
 */

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});

/**
 * hello-world test route:
 * it will change the "title" inside the index.hbs file that will be served to the client
 */
router.get('/hello-world', function(req, res, next) {
  res.render('index', { title: 'Hello world' });
});

/**
 * Responding with JSON data to the client
 */
router.get('/json', function(req, res, next) {
  res.json({data: "Hello from json"});
});

/**
 * Extracting a value from the client's request and return that value as JSON to the client
 */
router.get('/value/:v', function(req, res, next) {
  const number = req.params.v;
  res.json({number: number});
});

/**
 * POST request where we extract some body values, perform a simple check on the "title" and
 * returns 400 if the check fails or
 * returns JSON data with the body's values to the client
 */
router.post('/test-post', function(req, res){
  const title = req.body.title;
  const description = req.body.description;

  if(title === 'Twilight'){
    res.status(400).json({message: "I don't like that movie. Take this 400"})
  }

  res.json({title: title, description: description});
});

module.exports = router;
