var express = require('express');
var router = express.Router();

/**
 * File generated by the Express app template
 */

/* GET users listing. */
router.get('/', function(req, res, next) {
  res.send('respond with a resource');
});

module.exports = router;
